CREATE TABLE `user` (user_name varchar(100) NOT NULL UNIQUE, user_email varchar(100) NOT NULL UNIQUE, user_password varchar(255) NOT NULL, user_full_name varchar(255) NOT NULL, user_id int(11) NOT NULL AUTO_INCREMENT, user_phone_number int(20), user_balance double DEFAULT 0, profile_pic_path varchar(255), PRIMARY KEY (user_id));
CREATE TABLE permission (can_download_meme binary(1) DEFAULT '0' NOT NULL, can_share_meme binary(1) DEFAULT '0' NOT NULL, can_re_edit_template binary(1) NOT NULL, permission_id int(11) NOT NULL AUTO_INCREMENT, user_id int(11) NOT NULL, account_type varchar(50) NOT NULL, PRIMARY KEY (permission_id));
CREATE TABLE billing (billing_id int(11) NOT NULL AUTO_INCREMENT, user_id int(11) NOT NULL, billing_date datetime NOT NULL, withdraw_amount double, PRIMARY KEY (billing_id));
CREATE TABLE subscription (subscription_id int(10) NOT NULL AUTO_INCREMENT, subscription_start_date datetime NOT NULL, subscription_end_date datetime NOT NULL, user_id int(11) NOT NULL, subscription binary(1) DEFAULT '0' NOT NULL, PRIMARY KEY (subscription_id));
CREATE TABLE templates (template_id int(11) NOT NULL AUTO_INCREMENT, template_name varchar(255) NOT NULL, template_type varchar(50) NOT NULL, own_template binary(1) DEFAULT '0' NOT NULL, template_price double, useruser_id int(11) NOT NULL, template_path varchar(255) NOT NULL, PRIMARY KEY (template_id));
CREATE TABLE post_comment (comment_id int(11) NOT NULL AUTO_INCREMENT, comment varchar(255), comment_time datetime NULL, useruser_id int(11) NOT NULL, memesmeme_id int(11) NOT NULL, PRIMARY KEY (comment_id));
CREATE TABLE memes (meme_name varchar(255) NOT NULL UNIQUE, meme_id int(11) NOT NULL AUTO_INCREMENT, post_details varchar(255), meme_type varchar(50) NOT NULL, post_like int(10), post_time datetime NOT NULL, is_liked binary(1) DEFAULT '0', PRIMARY KEY (meme_id));
CREATE TABLE share (share_id int(11) NOT NULL AUTO_INCREMENT, share_time datetime NOT NULL, PRIMARY KEY (share_id));
CREATE TABLE cash_in (cash_in_id int(11) NOT NULL AUTO_INCREMENT, cash_in_ammount double NOT NULL, user_id int(11) NOT NULL, ac_number int(16) NOT NULL, ac_holder_name varchar(100) NOT NULL, ac_password varchar(255) NOT NULL, cash_in_date datetime NOT NULL, PRIMARY KEY (cash_in_id));
CREATE TABLE memes_share (memesmeme_id int(11) NOT NULL, shareshare_id int(11) NOT NULL, PRIMARY KEY (memesmeme_id, shareshare_id));
CREATE TABLE download (useruser_id int(11) NOT NULL, memesmeme_id int(11) NOT NULL, download_time datetime NULL, download_count int(10) DEFAULT 0, PRIMARY KEY (useruser_id, memesmeme_id));
CREATE TABLE purchase (useruser_id int(11) NOT NULL, templatestemplate_id int(11) NOT NULL, purchase_time datetime NOT NULL, PRIMARY KEY (useruser_id, templatestemplate_id));
CREATE TABLE user_memes (useruser_id int(11) NOT NULL, memesmeme_id int(11) NOT NULL, PRIMARY KEY (useruser_id, memesmeme_id));
ALTER TABLE permission ADD INDEX FKpermission285552 (user_id), ADD CONSTRAINT FKpermission285552 FOREIGN KEY (user_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE subscription ADD INDEX FKsubscripti536760 (user_id), ADD CONSTRAINT FKsubscripti536760 FOREIGN KEY (user_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE cash_in ADD INDEX FKcash_in310434 (user_id), ADD CONSTRAINT FKcash_in310434 FOREIGN KEY (user_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE memes_share ADD INDEX FKmemes_shar495983 (memesmeme_id), ADD CONSTRAINT FKmemes_shar495983 FOREIGN KEY (memesmeme_id) REFERENCES memes (meme_id) ON DELETE CASCADE;
ALTER TABLE memes_share ADD INDEX FKmemes_shar801703 (shareshare_id), ADD CONSTRAINT FKmemes_shar801703 FOREIGN KEY (shareshare_id) REFERENCES share (share_id) ON DELETE CASCADE;
ALTER TABLE post_comment ADD INDEX FKpost_comme157769 (useruser_id), ADD CONSTRAINT FKpost_comme157769 FOREIGN KEY (useruser_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE templates ADD INDEX FKtemplates459100 (useruser_id), ADD CONSTRAINT FKtemplates459100 FOREIGN KEY (useruser_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE download ADD INDEX FKdownload368567 (useruser_id), ADD CONSTRAINT FKdownload368567 FOREIGN KEY (useruser_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE download ADD INDEX FKdownload501354 (memesmeme_id), ADD CONSTRAINT FKdownload501354 FOREIGN KEY (memesmeme_id) REFERENCES memes (meme_id) ON DELETE CASCADE;
ALTER TABLE purchase ADD INDEX FKpurchase862466 (useruser_id), ADD CONSTRAINT FKpurchase862466 FOREIGN KEY (useruser_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE purchase ADD INDEX FKpurchase780218 (templatestemplate_id), ADD CONSTRAINT FKpurchase780218 FOREIGN KEY (templatestemplate_id) REFERENCES templates (template_id) ON DELETE CASCADE;
ALTER TABLE user_memes ADD INDEX FKuser_memes356795 (useruser_id), ADD CONSTRAINT FKuser_memes356795 FOREIGN KEY (useruser_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE user_memes ADD INDEX FKuser_memes510417 (memesmeme_id), ADD CONSTRAINT FKuser_memes510417 FOREIGN KEY (memesmeme_id) REFERENCES memes (meme_id) ON DELETE CASCADE;
ALTER TABLE billing ADD INDEX FKbilling496428 (user_id), ADD CONSTRAINT FKbilling496428 FOREIGN KEY (user_id) REFERENCES `user` (user_id) ON DELETE CASCADE;
ALTER TABLE post_comment ADD INDEX FKpost_comme24982 (memesmeme_id), ADD CONSTRAINT FKpost_comme24982 FOREIGN KEY (memesmeme_id) REFERENCES memes (meme_id) ON DELETE CASCADE;
